[build]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction",
  "npm ci",
  "npm run build",
  "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
  "chmod -R a+rw storage"
]

[start]
cmd = "php artisan migrate --force && php artisan config:clear && php artisan config:cache && php artisan event:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=8080"
